### ISSUE TITLE
The latest version failed to load on the Chinese server after the update on January 30, 2023

### ISSUE THREAD

**Issue by SitaNya** [awgil/ffxiv_bossmod#104]
First of all thanks for the great plugin
After the update of China server on January 30, 2023, this plugin can start but cannot draw skills
The following is my attempt to troubleshoot the problem, I hope it will be helpful for you to help me troubleshoot the problem, thank you very much for your assistance.
These contents are transferred from Chinese through google translation, please forgive me if there are grammatical errors

The version I used before was 0.0.0.76, which can be used normally before January 30, 2023 (it can also be loaded normally now, but the drawing is lost)

I tried to download the latest compilation results from a third-party website, `https://raw.githubusercontent.com/awgil/ffxiv_plugin_distribution/master/plugins/BossMod/latest.zip`

But it reports an error and fails to load. At the same time, I tried to compile the latest version "0.0.0.82" and the compilation was successful, but the same error was generated after putting it into dalamud

```
2023-02-02 03:46:26.434 +08:00 [ERR] [PLUGINM] During devPlugin scan, an unexpected error occurred
System.AggregateException: One or more errors occurred. (Exception of type 'Dalamud.Plugin.Internal.Exceptions.InvalidPluginException' was thrown.)
  ---> Dalamud.Plugin.Internal.Exceptions.InvalidPluginException: Exception of type 'Dalamud.Plugin.Internal.Exceptions.InvalidPluginException' was thrown.
    at Dalamud.Plugin.Internal.Types.LocalPlugin..ctor(FileInfo dllFile, LocalPluginManifest manifest)
    at Dalamud.Plugin.Internal.Types.LocalDevPlugin..ctor(FileInfo dllFile, LocalPluginManifest manifest)
    at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad)
    --- End of inner exception stack trace ---
    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
    at System.Threading.Tasks.Task.Wait()
    at Dalamud.Plugin.Internal.PluginManager.ScanDevPlugins()
2023-02-02 03:46:26.434 +08:00 [INF] [PLUGINM] Loading dev plugin Microsoft.CodeAnalysis.resources.dll
2023-02-02 03:46:26.435 +08:00 [ERR] [LOCALPLUGIN] Nothing inherits from IDalamudPlugin: E:\FF14\XIVLauncher\devPlugins\Splatoon\es\Microsoft.CodeAnalysis.resources.dll
2023-02-02 03:46:26.435 +08:00 [INF]
```

Also, I'm loading the plugin repo address

`https://raw.githubusercontent.com/awgil/ffxiv_plugin_distribution/master/pluginmaster.json`

Unable to find BossMod in the list like before

Your support is requested, thank you very much!

**Comment by awgil** [comment]
From what I understand, CN uses different client builds compared to EU, and as such has different opcodes for network messages. Since significant parts of plugin rely on parsing network messages, I'm surprised it even worked before.

I should probably rework the plugin to remove reliance on network messages someday. Until this is done, you can try updating opcodes manually to match CN version. If you are familiar with IDA, you can disassemble your exe and try running script below, then update opcodes in Protocol.cs, then build plugin locally from sources and use whatever you've built.

The script:
```
import idaapi
import ida_ida
import ida_bytes
import ida_search

packet_names = {
	121: 'RSVData',
	141: 'Countdown',
	142: 'CountdownCancel',
	201: 'StatusEffectList',
	202: 'StatusEffectListEureka',
	203: 'StatusEffectListBozja',
	204: 'StatusEffectListDouble',
	206: 'EffectResult1',
	207: 'EffectResult4',
	208: 'EffectResult8',
	209: 'EffectResult16',
	211: 'EffectResultBasic1',
	212: 'EffectResultBasic4',
	213: 'EffectResultBasic8',
	214: 'EffectResultBasic16',
	215: 'EffectResultBasic32',
	216: 'EffectResultBasic64',
	217: 'ActorControl',
	218: 'ActorControlSelf',
	219: 'ActorControlTarget',
	220: 'UpdateHpMpTp',
	221: 'ActionEffect1',
	224: 'ActionEffect8',
	225: 'ActionEffect16',
	226: 'ActionEffect24',
	227: 'ActionEffect32',
	230: 'StatusEffectListPlayer',
	232: 'UpdateRecastTimes',
	234: 'UpdateAllianceNormal',
	235: 'UpdateAllianceSmall',
	236: 'UpdatePartyMemberPositions',
	237: 'UpdateAllianceNormalMemberPositions',
	238: 'UpdateAllianceSmallMemberPositions',
	259: 'SpawnPlayer',
	260: 'SpawnNPC',
	261: 'SpawnBoss',
	262: 'DespawnCharacter',
	263: 'ActorMove',
	266: 'ActorSetPos',
	268: 'ActorCast',
	273: 'UpdateHate',
	274: 'UpdateHater',
	277: 'UpdateClassInfo',
	278: 'UpdateClassInfoEureka',
	279: 'UpdateClassInfoBozja',
	391: 'EnvControl',
	518: 'WaymarkPreset',
	519: 'Waymark',
	571: 'ActorGauge',
}

def find_next_func_by_sig(ea, pattern):
	return ida_search.find_binary(ea, ida_ida.inf_get_max_ea(), pattern, 16, ida_search.SEARCH_DOWN)

def find_single_func_by_sig(pattern):
	ea_first = find_next_func_by_sig(ida_ida.inf_get_min_ea(), pattern)
	if ea_first == idaapi.BADADDR:
		print(f'Could not find function by pattern {pattern}')
		return 0
	if find_next_func_by_sig(ea_first + 1, pattern) != idaapi.BADADDR:
		print(f'Multiple functions match pattern {pattern}')
		return 0
	return ea_first

def read_signed_byte(ea):
	v = ida_bytes.get_byte(ea)
	return v - 0x100 if v & 0x80 else v

def read_signed_dword(ea):
	v = ida_bytes.get_dword(ea)
	return v - 0x100000000 if v & 0x80000000 else v

def read_rva(ea):
	return ea + 4 + read_signed_dword(ea)

def get_vfoff_for_body(body):
	# assume each case has the following body:
	# mov rax, [rcx]
	# lea r9, [r10+10h]
	# jmp qword ptr [rax+<vfoff>]
	if ida_bytes.get_byte(body) != 0x48 or ida_bytes.get_byte(body + 1) != 0x8B or ida_bytes.get_byte(body + 2) != 0x01:
		return -1
	if ida_bytes.get_byte(body + 3) != 0x4D or ida_bytes.get_byte(body + 4) != 0x8D or ida_bytes.get_byte(body + 5) != 0x4A or ida_bytes.get_byte(body + 6) != 0x10:
		return -1
	if ida_bytes.get_byte(body + 7) != 0x48 or ida_bytes.get_byte(body + 8) != 0xFF:
		return -1
	sz = ida_bytes.get_byte(body + 9)
	if sz == 0x60:
		return read_signed_byte(body + 10)
	elif sz == 0xA0:
		return read_signed_dword(body + 10)
	else:
		return -1

def vfoff_to_index(vfoff):
	if vfoff < 0x10:
		return -1 # first two vfs are dtor and exec
	if (vfoff & 7) != 0:
		return -1 # vf contains qwords
	return (vfoff >> 3) - 2

class ffnetwork(idaapi.plugin_t):
	flags = idaapi.PLUGIN_UNL
	comment = 'Build opcode map'
	help = ''
	wanted_name = 'ffnetwork'
	wanted_hotkey = ''

	def init(self):
		return idaapi.PLUGIN_OK

	def run(self, arg=None):
		# assume func starts with:
		# mov rax, [r8+10h]
		# mov r10, [rax+38h]
		# movzx eax, word ptr [r10+2]
		# add eax, -<min_case>
		# cmp eax, <max_case-min_case>
		# ja <default_off>
		# lea r11, <__ImageBase_off>
		# cdqe
		# mov r9d, ds::<jumptable_rva>[r11+rax*4]
		func = find_single_func_by_sig('49 8B 40 10  4C 8B 50 38  41 0F B7 42 02  83 C0 ??  3D ?? ?? ?? ??  0F 87 ?? ?? ?? ??  4C 8D 1D ?? ?? ?? ??  48 98  45 8B 8C 83 ?? ?? ?? ??')
		if func == 0:
			return
		min_case = -read_signed_byte(func + 15) # this is a negative
		jumptable_size = read_signed_dword(func + 17) + 1
		def_addr = read_rva(func + 23)
		imagebase = read_rva(func + 30)
		jumptable = imagebase + read_signed_dword(func + 40)
		opcodemap = {}
		for i in range(jumptable_size):
			body = imagebase + read_signed_dword(jumptable + 4 * i)
			if body == def_addr:
				continue
			case = i + min_case
			voff = get_vfoff_for_body(body)
			index = vfoff_to_index(voff)
			if index < 0:
				print(f'Unexpected body for case {case}')
				continue
			if index in opcodemap:
				print(f'Multiple opcodes map to single operation {index}: {hex(opcodemap[index])} and {hex(case)}')
				continue
			opcodemap[index] = case
		for k, v in sorted(opcodemap.items()):
			name = packet_names[k] if k in packet_names else f'Packet{k}'
			print(f'{name} = {hex(v)}')

	def term(self):
		pass

def PLUGIN_ENTRY():
	return ffnetwork()
```

**Comment by awgil** [comment]
Outdated
