### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by SamleTT** [awgil/ffxiv_bossmod#153]
Hello, when I installed it, he reported an error, so I found the log you said, this is the data he provided

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: Can't find a signature of 74 20 81 FD F5 0D 00 00
   at Dalamud.Game.SigScanner.Scan(IntPtr baseAddress, Int32 size, String signature)
   at Dalamud.Game.SigScanner.ScanModule(String signature)
   at BossMod.ActionManagerEx..ctor() in E:\sources\ff14\BossMod\BossMod\Framework\ActionManagerEx.cs:line 170
   at BossMod.Plugin..ctor(DalamudPluginInterface dalamud, CommandManager commandManager) in E:\sources\ff14\BossMod\BossMod\Framework\Plugin.cs:line 49
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.ConstructorInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects)
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading)
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad)
   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason)

**Comment by awgil** [comment]
Are you playing CN/KR version by chance? I think they have different builds than global, I don't really know anything about them.

**Comment by awgil** [comment]
Outdated.
