### ISSUE TITLE
Plugin soft crashed, this is the exception I received, thanks!

### ISSUE THREAD

**Issue by abranon** [awgil/ffxiv_bossmod#17]
2022-05-24 20:50:52.124 -05:00 [ERR] [BossMod] UiBuilder OnBuildUi caught exception
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at BossMod.BossModuleManager.UnloadModule(Int32 index) in E:\sources\ff14\BossMod\BossMod\BossModule\BossModuleManager.cs:line 190
   at BossMod.BossModuleManager.ConfigChanged(Object sender, EventArgs args) in E:\sources\ff14\BossMod\BossMod\BossModule\BossModuleManager.cs:line 238
   at BossMod.ConfigNode.NotifyModified() in E:\sources\ff14\BossMod\BossMod\Config\ConfigNode.cs:line 66
   at BossMod.ConfigNode.Draw() in E:\sources\ff14\BossMod\BossMod\Config\ConfigNode.cs:line 37
   at BossMod.ConfigNode.Draw() in E:\sources\ff14\BossMod\BossMod\Config\ConfigNode.cs:line 42
   at BossMod.WindowManager.Window.Draw() in E:\sources\ff14\BossMod\BossMod\Framework\WindowManager.cs:line 38
   at BossMod.WindowManager.DrawAll() in E:\sources\ff14\BossMod\BossMod\Framework\WindowManager.cs:line 89
   at Dalamud.Interface.UiBuilder.OnDraw() in C:\goatsoft\companysecrets\dalamud\Interface\UiBuilder.cs:line 305
2022-05-24 20:50:52.131 -05:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wNS0yNFQyMDo1MDo1Mi4xMzEzNjQyLTA1OjAwIiwiSW5mbyI6IlN5c3RlbS5Bcmd1bWVudE91dE9mUmFuZ2VFeGNlcHRpb246IEluZGV4IHdhcyBvdXQgb2YgcmFuZ2UuIE11c3QgYmUgbm9uLW5lZ2F0aXZlIGFuZCBsZXNzIHRoYW4gdGhlIHNpemUgb2YgdGhlIGNvbGxlY3Rpb24uIChQYXJhbWV0ZXIgJ2luZGV4JylcclxuICAgYXQgQm9zc01vZC5Cb3NzTW9kdWxlTWFuYWdlci5VbmxvYWRNb2R1bGUoSW50MzIgaW5kZXgpIGluIEU6XFxzb3VyY2VzXFxmZjE0XFxCb3NzTW9kXFxCb3NzTW9kXFxCb3NzTW9kdWxlXFxCb3NzTW9kdWxlTWFuYWdlci5jczpsaW5lIDE5MFxyXG4gICBhdCBCb3NzTW9kLkJvc3NNb2R1bGVNYW5hZ2VyLkNvbmZpZ0NoYW5nZWQoT2JqZWN0IHNlbmRlciwgRXZlbnRBcmdzIGFyZ3MpIGluIEU6XFxzb3VyY2VzXFxmZjE0XFxCb3NzTW9kXFxCb3NzTW9kXFxCb3NzTW9kdWxlXFxCb3NzTW9kdWxlTWFuYWdlci5jczpsaW5lIDIzOFxyXG4gICBhdCBCb3NzTW9kLkNvbmZpZ05vZGUuTm90aWZ5TW9kaWZpZWQoKSBpbiBFOlxcc291cmNlc1xcZmYxNFxcQm9zc01vZFxcQm9zc01vZFxcQ29uZmlnXFxDb25maWdOb2RlLmNzOmxpbmUgNjZcclxuICAgYXQgQm9zc01vZC5Db25maWdOb2RlLkRyYXcoKSBpbiBFOlxcc291cmNlc1xcZmYxNFxcQm9zc01vZFxcQm9zc01vZFxcQ29uZmlnXFxDb25maWdOb2RlLmNzOmxpbmUgMzdcclxuICAgYXQgQm9zc01vZC5Db25maWdOb2RlLkRyYXcoKSBpbiBFOlxcc291cmNlc1xcZmYxNFxcQm9zc01vZFxcQm9zc01vZFxcQ29uZmlnXFxDb25maWdOb2RlLmNzOmxpbmUgNDJcclxuICAgYXQgQm9zc01vZC5XaW5kb3dNYW5hZ2VyLldpbmRvdy5EcmF3KCkgaW4gRTpcXHNvdXJjZXNcXGZmMTRcXEJvc3NNb2RcXEJvc3NNb2RcXEZyYW1ld29ya1xcV2luZG93TWFuYWdlci5jczpsaW5lIDM4XHJcbiAgIGF0IEJvc3NNb2QuV2luZG93TWFuYWdlci5EcmF3QWxsKCkgaW4gRTpcXHNvdXJjZXNcXGZmMTRcXEJvc3NNb2RcXEJvc3NNb2RcXEZyYW1ld29ya1xcV2luZG93TWFuYWdlci5jczpsaW5lIDg5XHJcbiAgIGF0IERhbGFtdWQuSW50ZXJmYWNlLlVpQnVpbGRlci5PbkRyYXcoKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxJbnRlcmZhY2VcXFVpQnVpbGRlci5jczpsaW5lIDMwNSIsIkNvbnRleHQiOiJbXCJCb3NzTW9kXCJdIFVpQnVpbGRlciBPbkJ1aWxkVWkgY2F1Z2h0IGV4Y2VwdGlvbiJ9

**Comment by awgil** [comment]
Fixed in latest version.
