### ISSUE TITLE
settings window

### ISSUE THREAD

**Issue by CyansZhang** [awgil/ffxiv_bossmod#322]
bossmod can not open settings window
ver.0.0.0.141

**Comment by CarnifexOptimus** [comment]
works fine for me, do you use the original version or a fork?

**Comment by LvGuichen0** [comment]
I have the same issue. But my plugin is ver.0.0.0.147. Have you solved this issue?

**Comment by 851608438** [comment]
same issue, and i check the log:

2024-04-14 22:28:26.684 +08:00 [ERR] Exception during raise of Void OpenConfigUI()
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string. (Parameter 'startIndex')
   at System.String.ThrowSubstringArgumentOutOfRange(Int32 startIndex, Int32 length)
   at System.String.Substring(Int32 startIndex)
   at BossMod.ModuleViewer.Classify(Info module) in /home/runner/work/ffxiv_bossmod/ffxiv_bossmod/BossMod/Config/ModuleViewer.cs:line 263
   at BossMod.ModuleViewer..ctor() in /home/runner/work/ffxiv_bossmod/ffxiv_bossmod/BossMod/Config/ModuleViewer.cs:line 77
   at BossMod.ConfigUI..ctor(ConfigRoot config, WorldState ws) in /home/runner/work/ffxiv_bossmod/ffxiv_bossmod/BossMod/Config/ConfigUI.cs:line 25
   at BossMod.Plugin.OpenConfigUI() in /home/runner/work/ffxiv_bossmod/ffxiv_bossmod/BossMod/Framework/Plugin.cs:line 134
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act)

**Comment by CarnifexOptimus** [comment]
are you using the international version of FF14 or the chinese version? I think you might need to use the chinese fork if you are using the chinese version of the game.

**Comment by awgil** [comment]
Outdated.
