### ISSUE TITLE
Initialization failing on v0.0.0.191 due to debugging

### ISSUE THREAD

**Issue by Phenrei** [awgil/ffxiv_bossmod#403]
Log line I'm getting after the newest update, have rebooted game and still get this issue:

```
| ERR | [LOCALPLUGIN] Exception during plugin initialization
	System.AggregateException: Failed to create BossMod.Plugin (ctor invocation) (Exception has been thrown by the target of an invocation.)
	 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	 ---> System.Collections.Generic.KeyNotFoundException: Can't find a signature of 48 8D 0D ?? ?? ?? ?? E8 ?? ?? ?? ?? 3C 01 75 1E 48 8D 0D
	   at Dalamud.Game.SigScanner.Scan(IntPtr baseAddress, Int32 size, String signature) in C:\goatsoft\companysecrets\dalamud\\Game\SigScanner.cs:line 122
	   at Dalamud.Game.SigScanner.ScanText(String signature) in C:\goatsoft\companysecrets\dalamud\\Game\SigScanner.cs:line 278
	   at Dalamud.Game.SigScanner.GetStaticAddressFromSig(String signature, Int32 offset) in C:\goatsoft\companysecrets\dalamud\\Game\SigScanner.cs:line 159
	   at BossMod.DebugInput..ctor(RotationModuleManager autorot) in /home/runner/work/ffxiv_bossmod/ffxiv_bossmod/BossMod/Debug/DebugInput.cs:line 116
	   at BossMod.MainDebugWindow..ctor(WorldState ws, RotationModuleManager autorot, ActionManagerEx amex) in /home/runner/work/ffxiv_bossmod/ffxiv_bossmod/BossMod/Debug/MainDebugWindow.cs:line 16
	   at BossMod.Plugin..ctor(IDalamudPluginInterface dalamud, ICommandManager commandManager, ISigScanner sigScanner, IDataManager dataManager) in /home/runner/work/ffxiv_bossmod/ffxiv_bossmod/BossMod/Framework/Plugin.cs:line 90
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   --- End of inner exception stack trace ---
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
	   at Dalamud.IoC.Internal.ServiceContainer.<>c__DisplayClass10_0.<CreateAsync>b__0() in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 117
	--- End of stack trace from previous location ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 129
	   --- End of inner exception stack trace ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 136
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<LoadAsync>g__Create|69_1() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 425
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 422
```

Appears the sig you added back in in this commit isn't being found in my game: https://github.com/awgil/ffxiv_bossmod/commit/2e9ea6234bf383a0d1eb088a84c6cdd95ad39523

Attempted with all other mods disabled and same behavior occurs.

**Comment by awgil** [comment]
Should be fixed now.
