### ISSUE TITLE
crash after duty end

### ISSUE THREAD

**Issue by Jaksuhn** [awgil/ffxiv_bossmod#58]
Was farming garuda ex for an achievement and after one of them, upon trying to leave the instance, the game crashed. Logs point to bossmod

relevant portion:
```
2022-10-07 12:01:35.387 +11:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0xMC0wN1QxMjowMTozNS4zODcwNzI1KzExOjAwIiwiSW5mbyI6IlN5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLktleU5vdEZvdW5kRXhjZXB0aW9uOiBUaGUgZ2l2ZW4ga2V5ICcyNzA4OTk3MzMnIHdhcyBub3QgcHJlc2VudCBpbiB0aGUgZGljdGlvbmFyeS5cclxuICAgYXQgU3lzdGVtLkNvbGxlY3Rpb25zLkdlbmVyaWMuRGljdGlvbmFyeWAyLmdldF9JdGVtKFRLZXkga2V5KVxyXG4gICBhdCBCb3NzTW9kLkFjdG9yU3RhdGUuT3BlcmF0aW9uLkV4ZWMoV29ybGRTdGF0ZSB3cykgaW4gRTpcXHNvdXJjZXNcXGZmMTRcXEJvc3NNb2RcXEJvc3NNb2RcXERhdGFcXEFjdG9yU3RhdGUuY3M6bGluZSAyNlxyXG4gICBhdCBCb3NzTW9kLldvcmxkU3RhdGUuT3BlcmF0aW9uLkV4ZWN1dGUoV29ybGRTdGF0ZSB3cykgaW4gRTpcXHNvdXJjZXNcXGZmMTRcXEJvc3NNb2RcXEJvc3NNb2RcXERhdGFcXFdvcmxkU3RhdGUuY3M6bGluZSAzM1xyXG4gICBhdCBCb3NzTW9kLldvcmxkU3RhdGVHYW1lLlJlbW92ZUFjdG9yKEFjdG9yIGFjdG9yKSBpbiBFOlxcc291cmNlc1xcZmYxNFxcQm9zc01vZFxcQm9zc01vZFxcRnJhbWV3b3JrXFxXb3JsZFN0YXRlR2FtZS5jczpsaW5lIDEyMFxyXG4gICBhdCBCb3NzTW9kLldvcmxkU3RhdGVHYW1lLlVwZGF0ZUFjdG9ycygpIGluIEU6XFxzb3VyY2VzXFxmZjE0XFxCb3NzTW9kXFxCb3NzTW9kXFxGcmFtZXdvcmtcXFdvcmxkU3RhdGVHYW1lLmNzOmxpbmUgOThcclxuICAgYXQgQm9zc01vZC5Xb3JsZFN0YXRlR2FtZS5VcGRhdGUoVGltZVNwYW4gcHJldkZyYW1lUGVyZikgaW4gRTpcXHNvdXJjZXNcXGZmMTRcXEJvc3NNb2RcXEJvc3NNb2RcXEZyYW1ld29ya1xcV29ybGRTdGF0ZUdhbWUuY3M6bGluZSA3NlxyXG4gICBhdCBCb3NzTW9kLlBsdWdpbi5EcmF3VUkoKSBpbiBFOlxcc291cmNlc1xcZmYxNFxcQm9zc01vZFxcQm9zc01vZFxcRnJhbWV3b3JrXFxQbHVnaW4uY3M6bGluZSAxMjFcclxuICAgYXQgRGFsYW11ZC5VdGlsaXR5LkV2ZW50SGFuZGxlckV4dGVuc2lvbnMuSGFuZGxlSW52b2tlKEFjdGlvbiBhY3QpIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFV0aWxpdHlcXEV2ZW50SGFuZGxlckV4dGVuc2lvbnMuY3M6bGluZSA5NiIsIkNvbnRleHQiOiJFeGNlcHRpb24gZHVyaW5nIHJhaXNlIG9mIFwiVm9pZCBEcmF3VUkoKVwiIn0=
2022-10-07 12:01:35.386 +11:00 [ERR] Exception during raise of Void DrawUI()
System.Collections.Generic.KeyNotFoundException: The given key '270899733' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at BossMod.ActorState.Operation.Exec(WorldState ws) in E:\sources\ff14\BossMod\BossMod\Data\ActorState.cs:line 26
   at BossMod.WorldState.Operation.Execute(WorldState ws) in E:\sources\ff14\BossMod\BossMod\Data\WorldState.cs:line 33
   at BossMod.WorldStateGame.RemoveActor(Actor actor) in E:\sources\ff14\BossMod\BossMod\Framework\WorldStateGame.cs:line 120
   at BossMod.WorldStateGame.UpdateActors() in E:\sources\ff14\BossMod\BossMod\Framework\WorldStateGame.cs:line 98
   at BossMod.WorldStateGame.Update(TimeSpan prevFramePerf) in E:\sources\ff14\BossMod\BossMod\Framework\WorldStateGame.cs:line 76
   at BossMod.Plugin.DrawUI() in E:\sources\ff14\BossMod\BossMod\Framework\Plugin.cs:line 121
   at Dalamud.Utility.EventHandlerExtensions.HandleInvoke(Action act) in C:\goatsoft\companysecrets\dalamud\Utility\EventHandlerExtensions.cs:line 96
```
[dalamud.old.log](https://github.com/awgil/ffxiv_bossmod/files/9729796/dalamud.old.log)

**Comment by awgil** [comment]
This is weird, probably something wrong happened before first exception. Fixed by slightly rearranging order of operations, so that if actor removal throws, at least we won't try to delete it again on all future frames. Will be released as part of next version.
